### ISSUE TITLE
[TODO]: Custom error-handling middleware for API requests

### ISSUE THREAD

**Issue by connoro7** [connoro7/console.shop#18]
Express's default error handler is handling API requests that aren't correctly formatted.
Want to have the server handle all of the errors, and not send any default error responses.

At [/api/products/5](http://localhost:5000/api/products/5), getting this error:

```
CastError: Cast to ObjectId failed for value "5" at path "_id" for model "Product"
    at model.Query.exec (/Users/connor/__Dev/console.shop/node_modules/mongoose/lib/query.js:4358:21)
    at model.Query.Query.then (/Users/connor/__Dev/console.shop/node_modules/mongoose/lib/query.js:4450:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by connoro7** [comment]
## Closed
> Fixed by PR #19 and PR #20
